//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 2 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")
    /// Color `BackgroundCellColor`.
    static let backgroundCellColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "BackgroundCellColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "BackgroundCellColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func backgroundCellColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.backgroundCellColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "BackgroundCellColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func backgroundCellColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.backgroundCellColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `GoogleService-Info.plist`.
    static let googleServiceInfoPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "GoogleService-Info", pathExtension: "plist")

    /// `bundle.url(forResource: "GoogleService-Info", withExtension: "plist")`
    static func googleServiceInfoPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.googleServiceInfoPlist
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 7 images.
  struct image {
    /// Image `Five`.
    static let five = Rswift.ImageResource(bundle: R.hostingBundle, name: "Five")
    /// Image `Four`.
    static let four = Rswift.ImageResource(bundle: R.hostingBundle, name: "Four")
    /// Image `One`.
    static let one = Rswift.ImageResource(bundle: R.hostingBundle, name: "One")
    /// Image `Three`.
    static let three = Rswift.ImageResource(bundle: R.hostingBundle, name: "Three")
    /// Image `Two`.
    static let two = Rswift.ImageResource(bundle: R.hostingBundle, name: "Two")
    /// Image `picture`.
    static let picture = Rswift.ImageResource(bundle: R.hostingBundle, name: "picture")
    /// Image `splashMainIcon`.
    static let splashMainIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "splashMainIcon")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Five", bundle: ..., traitCollection: ...)`
    static func five(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.five, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Four", bundle: ..., traitCollection: ...)`
    static func four(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.four, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "One", bundle: ..., traitCollection: ...)`
    static func one(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.one, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Three", bundle: ..., traitCollection: ...)`
    static func three(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.three, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Two", bundle: ..., traitCollection: ...)`
    static func two(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.two, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "picture", bundle: ..., traitCollection: ...)`
    static func picture(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.picture, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "splashMainIcon", bundle: ..., traitCollection: ...)`
    static func splashMainIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.splashMainIcon, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 8 localization tables.
  struct string {
    /// This `R.string.cellID` struct is generated, and contains static references to 4 localization keys.
    struct cellID {
      /// Value: CarouselCollectionViewCellID
      static let carouselCollectionViewCell = Rswift.StringResource(key: "carouselCollectionViewCell", tableName: "CellID", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: CharacterTableViewController
      static let characterTableViewController = Rswift.StringResource(key: "characterTableViewController", tableName: "CellID", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: EpisodeTableViewController
      static let episodeTableViewController = Rswift.StringResource(key: "episodeTableViewController", tableName: "CellID", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: LocationTableViewController
      static let locationTableViewController = Rswift.StringResource(key: "locationTableViewController", tableName: "CellID", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: CarouselCollectionViewCellID
      static func carouselCollectionViewCell(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("carouselCollectionViewCell", tableName: "CellID", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CellID", preferredLanguages: preferredLanguages) else {
          return "carouselCollectionViewCell"
        }

        return NSLocalizedString("carouselCollectionViewCell", tableName: "CellID", bundle: bundle, comment: "")
      }

      /// Value: CharacterTableViewController
      static func characterTableViewController(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("characterTableViewController", tableName: "CellID", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CellID", preferredLanguages: preferredLanguages) else {
          return "characterTableViewController"
        }

        return NSLocalizedString("characterTableViewController", tableName: "CellID", bundle: bundle, comment: "")
      }

      /// Value: EpisodeTableViewController
      static func episodeTableViewController(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("episodeTableViewController", tableName: "CellID", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CellID", preferredLanguages: preferredLanguages) else {
          return "episodeTableViewController"
        }

        return NSLocalizedString("episodeTableViewController", tableName: "CellID", bundle: bundle, comment: "")
      }

      /// Value: LocationTableViewController
      static func locationTableViewController(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("locationTableViewController", tableName: "CellID", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CellID", preferredLanguages: preferredLanguages) else {
          return "locationTableViewController"
        }

        return NSLocalizedString("locationTableViewController", tableName: "CellID", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.colors` struct is generated, and contains static references to 2 localization keys.
    struct colors {
      /// Value: BackgroundButtonColor
      static let backgroundButtonColor = Rswift.StringResource(key: "backgroundButtonColor", tableName: "Colors", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: BackgroundCellColor
      static let backgroundCellColor = Rswift.StringResource(key: "backgroundCellColor", tableName: "Colors", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: BackgroundButtonColor
      static func backgroundButtonColor(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("backgroundButtonColor", tableName: "Colors", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Colors", preferredLanguages: preferredLanguages) else {
          return "backgroundButtonColor"
        }

        return NSLocalizedString("backgroundButtonColor", tableName: "Colors", bundle: bundle, comment: "")
      }

      /// Value: BackgroundCellColor
      static func backgroundCellColor(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("backgroundCellColor", tableName: "Colors", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Colors", preferredLanguages: preferredLanguages) else {
          return "backgroundCellColor"
        }

        return NSLocalizedString("backgroundCellColor", tableName: "Colors", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.errors` struct is generated, and contains static references to 2 localization keys.
    struct errors {
      /// Value: Failed
      static let failed = Rswift.StringResource(key: "failed", tableName: "Errors", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: init(coder:) has not been implemented
      static let initCoderHasNotBeenImplemented = Rswift.StringResource(key: "init(coder:) has not been implemented", tableName: "Errors", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Failed
      static func failed(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("failed", tableName: "Errors", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Errors", preferredLanguages: preferredLanguages) else {
          return "failed"
        }

        return NSLocalizedString("failed", tableName: "Errors", bundle: bundle, comment: "")
      }

      /// Value: init(coder:) has not been implemented
      static func initCoderHasNotBeenImplemented(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("init(coder:) has not been implemented", tableName: "Errors", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Errors", preferredLanguages: preferredLanguages) else {
          return "init(coder:) has not been implemented"
        }

        return NSLocalizedString("init(coder:) has not been implemented", tableName: "Errors", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.fonts` struct is generated, and contains static references to 2 localization keys.
    struct fonts {
      /// Value: Avenir-Heavy
      static let avenirHeavy = Rswift.StringResource(key: "avenirHeavy", tableName: "Fonts", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Avenir-Medium
      static let avenirMedium = Rswift.StringResource(key: "avenirMedium", tableName: "Fonts", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Avenir-Heavy
      static func avenirHeavy(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("avenirHeavy", tableName: "Fonts", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Fonts", preferredLanguages: preferredLanguages) else {
          return "avenirHeavy"
        }

        return NSLocalizedString("avenirHeavy", tableName: "Fonts", bundle: bundle, comment: "")
      }

      /// Value: Avenir-Medium
      static func avenirMedium(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("avenirMedium", tableName: "Fonts", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Fonts", preferredLanguages: preferredLanguages) else {
          return "avenirMedium"
        }

        return NSLocalizedString("avenirMedium", tableName: "Fonts", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.imageCarouselSet` struct is generated, and contains static references to 5 localization keys.
    struct imageCarouselSet {
      /// Value: Five
      static let fiveImage = Rswift.StringResource(key: "fiveImage", tableName: "ImageCarouselSet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Four
      static let fourImage = Rswift.StringResource(key: "fourImage", tableName: "ImageCarouselSet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: One
      static let oneImage = Rswift.StringResource(key: "oneImage", tableName: "ImageCarouselSet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Three
      static let threeImage = Rswift.StringResource(key: "threeImage", tableName: "ImageCarouselSet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Two
      static let twoImage = Rswift.StringResource(key: "twoImage", tableName: "ImageCarouselSet", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Five
      static func fiveImage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("fiveImage", tableName: "ImageCarouselSet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ImageCarouselSet", preferredLanguages: preferredLanguages) else {
          return "fiveImage"
        }

        return NSLocalizedString("fiveImage", tableName: "ImageCarouselSet", bundle: bundle, comment: "")
      }

      /// Value: Four
      static func fourImage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("fourImage", tableName: "ImageCarouselSet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ImageCarouselSet", preferredLanguages: preferredLanguages) else {
          return "fourImage"
        }

        return NSLocalizedString("fourImage", tableName: "ImageCarouselSet", bundle: bundle, comment: "")
      }

      /// Value: One
      static func oneImage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("oneImage", tableName: "ImageCarouselSet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ImageCarouselSet", preferredLanguages: preferredLanguages) else {
          return "oneImage"
        }

        return NSLocalizedString("oneImage", tableName: "ImageCarouselSet", bundle: bundle, comment: "")
      }

      /// Value: Three
      static func threeImage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("threeImage", tableName: "ImageCarouselSet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ImageCarouselSet", preferredLanguages: preferredLanguages) else {
          return "threeImage"
        }

        return NSLocalizedString("threeImage", tableName: "ImageCarouselSet", bundle: bundle, comment: "")
      }

      /// Value: Two
      static func twoImage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("twoImage", tableName: "ImageCarouselSet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ImageCarouselSet", preferredLanguages: preferredLanguages) else {
          return "twoImage"
        }

        return NSLocalizedString("twoImage", tableName: "ImageCarouselSet", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.imageSet` struct is generated, and contains static references to 5 localization keys.
    struct imageSet {
      /// Value: globe
      static let locations = Rswift.StringResource(key: "locations", tableName: "ImageSet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: person.2
      static let characters = Rswift.StringResource(key: "characters", tableName: "ImageSet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: picture
      static let mookPicture = Rswift.StringResource(key: "mookPicture", tableName: "ImageSet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: sparkles.tv
      static let episodes = Rswift.StringResource(key: "episodes", tableName: "ImageSet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: splashMainIcon
      static let mainScreenIcon = Rswift.StringResource(key: "mainScreenIcon", tableName: "ImageSet", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: globe
      static func locations(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("locations", tableName: "ImageSet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ImageSet", preferredLanguages: preferredLanguages) else {
          return "locations"
        }

        return NSLocalizedString("locations", tableName: "ImageSet", bundle: bundle, comment: "")
      }

      /// Value: person.2
      static func characters(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("characters", tableName: "ImageSet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ImageSet", preferredLanguages: preferredLanguages) else {
          return "characters"
        }

        return NSLocalizedString("characters", tableName: "ImageSet", bundle: bundle, comment: "")
      }

      /// Value: picture
      static func mookPicture(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("mookPicture", tableName: "ImageSet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ImageSet", preferredLanguages: preferredLanguages) else {
          return "mookPicture"
        }

        return NSLocalizedString("mookPicture", tableName: "ImageSet", bundle: bundle, comment: "")
      }

      /// Value: sparkles.tv
      static func episodes(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("episodes", tableName: "ImageSet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ImageSet", preferredLanguages: preferredLanguages) else {
          return "episodes"
        }

        return NSLocalizedString("episodes", tableName: "ImageSet", bundle: bundle, comment: "")
      }

      /// Value: splashMainIcon
      static func mainScreenIcon(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("mainScreenIcon", tableName: "ImageSet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ImageSet", preferredLanguages: preferredLanguages) else {
          return "mainScreenIcon"
        }

        return NSLocalizedString("mainScreenIcon", tableName: "ImageSet", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.titles` struct is generated, and contains static references to 14 localization keys.
    struct titles {
      /// Value: Black
      static let black = Rswift.StringResource(key: "black", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Characters
      static let characters = Rswift.StringResource(key: "characters", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: CoreDataModel
      static let coreDataName = Rswift.StringResource(key: "CoreDataName", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Episodes
      static let episodes = Rswift.StringResource(key: "episodes", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Failed
      static let failed = Rswift.StringResource(key: "failed", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Locations
      static let locations = Rswift.StringResource(key: "locations", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: OK
      static let ok = Rswift.StringResource(key: "ok", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Search
      static let search = Rswift.StringResource(key: "search", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: The Rick and Morty
      static let rickAndMorty = Rswift.StringResource(key: "rickAndMorty", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: air date: %@
      static let airDate = Rswift.StringResource(key: "air date:", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: episode: %@
      static let episode = Rswift.StringResource(key: "episode:", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: gender:
      static let genders = Rswift.StringResource(key: "genders", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: gender: %@
      static let gender = Rswift.StringResource(key: "gender:", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: species: %@
      static let species = Rswift.StringResource(key: "species:", tableName: "Titles", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Black
      static func black(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("black", tableName: "Titles", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "black"
        }

        return NSLocalizedString("black", tableName: "Titles", bundle: bundle, comment: "")
      }

      /// Value: Characters
      static func characters(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("characters", tableName: "Titles", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "characters"
        }

        return NSLocalizedString("characters", tableName: "Titles", bundle: bundle, comment: "")
      }

      /// Value: CoreDataModel
      static func coreDataName(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("CoreDataName", tableName: "Titles", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "CoreDataName"
        }

        return NSLocalizedString("CoreDataName", tableName: "Titles", bundle: bundle, comment: "")
      }

      /// Value: Episodes
      static func episodes(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("episodes", tableName: "Titles", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "episodes"
        }

        return NSLocalizedString("episodes", tableName: "Titles", bundle: bundle, comment: "")
      }

      /// Value: Failed
      static func failed(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("failed", tableName: "Titles", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "failed"
        }

        return NSLocalizedString("failed", tableName: "Titles", bundle: bundle, comment: "")
      }

      /// Value: Locations
      static func locations(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("locations", tableName: "Titles", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "locations"
        }

        return NSLocalizedString("locations", tableName: "Titles", bundle: bundle, comment: "")
      }

      /// Value: OK
      static func ok(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("ok", tableName: "Titles", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "ok"
        }

        return NSLocalizedString("ok", tableName: "Titles", bundle: bundle, comment: "")
      }

      /// Value: Search
      static func search(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("search", tableName: "Titles", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "search"
        }

        return NSLocalizedString("search", tableName: "Titles", bundle: bundle, comment: "")
      }

      /// Value: The Rick and Morty
      static func rickAndMorty(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("rickAndMorty", tableName: "Titles", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "rickAndMorty"
        }

        return NSLocalizedString("rickAndMorty", tableName: "Titles", bundle: bundle, comment: "")
      }

      /// Value: air date: %@
      static func airDate(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("air date:", tableName: "Titles", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "air date:"
        }

        let format = NSLocalizedString("air date:", tableName: "Titles", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// Value: episode: %@
      static func episode(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("episode:", tableName: "Titles", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "episode:"
        }

        let format = NSLocalizedString("episode:", tableName: "Titles", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// Value: gender:
      static func genders(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("genders", tableName: "Titles", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "genders"
        }

        return NSLocalizedString("genders", tableName: "Titles", bundle: bundle, comment: "")
      }

      /// Value: gender: %@
      static func gender(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("gender:", tableName: "Titles", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "gender:"
        }

        let format = NSLocalizedString("gender:", tableName: "Titles", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// Value: species: %@
      static func species(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("species:", tableName: "Titles", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Titles", preferredLanguages: preferredLanguages) else {
          return "species:"
        }

        let format = NSLocalizedString("species:", tableName: "Titles", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      fileprivate init() {}
    }

    /// This `R.string.userDefaultsKey` struct is generated, and contains static references to 2 localization keys.
    struct userDefaultsKey {
      /// Value: networkServiceURL
      static let networkServiceURL = Rswift.StringResource(key: "networkServiceURL", tableName: "UserDefaultsKey", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: switcher
      static let switcher = Rswift.StringResource(key: "switcher", tableName: "UserDefaultsKey", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: networkServiceURL
      static func networkServiceURL(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("networkServiceURL", tableName: "UserDefaultsKey", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "UserDefaultsKey", preferredLanguages: preferredLanguages) else {
          return "networkServiceURL"
        }

        return NSLocalizedString("networkServiceURL", tableName: "UserDefaultsKey", bundle: bundle, comment: "")
      }

      /// Value: switcher
      static func switcher(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("switcher", tableName: "UserDefaultsKey", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "UserDefaultsKey", preferredLanguages: preferredLanguages) else {
          return "switcher"
        }

        return NSLocalizedString("switcher", tableName: "UserDefaultsKey", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if UIKit.UIImage(named: "splashMainIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'splashMainIcon' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
